project:
  type: default
  output-dir: docx
  render:
    - report.qmd

execute:
  echo: false
  warning: false
  message: false
  freeze: false

format:
  docx:
    toc: true
    toc-depth: 2
    number-sections: true
    reference-doc: reference.docx
    toc-title: "Table des matières" 

params:
  lang: "fr"
  territories:
    - cotriguacu
    - paragominas
    - guaviare
    - madre_de_dios

profiles:
  fr:
    params:
      lang: fr
    format:
      docx:
        toc-title: "Table des matières"
  pt:
    params:
      lang: pt
    format:
      docx:
        toc-title: "Sumário"
  es:
    params:
      lang: es
    format:
      docx:
        toc-title: "Tabla de contenidos"
  en:
    params:
      lang: en
    format:
      docx:
        toc-title: "Table of contents"
